version: '3.8'

services:
  postgres-db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: diagram-sequence-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mongo-db:
    image: mongo:lasted
    restart: always
    ports:
      - "27017:27017"
    container_name: diagram-sequence-mongo
    volumes:
      - ./mongo-data:/data/db